### ISSUE TITLE
TBD: CFP card/page

### ISSUE THREAD

**Issue by sidsrivast** [TathagataChakraborti/ICAPS2019#13]
Retain the left panel and banner; fill the rest with cards for calls

**Comment by TathagataChakraborti** [comment]
Done, need content for cards.

**Comment by sidsrivast** [comment]
Banner changes got clobbered… The white rectangle sticks out and the font doesn’t match.

**Comment by TathagataChakraborti** [comment]
Yeah I know, the white one was for the white version, it's a placeholder for now. The other banner repeats a picture and also the logo gets killed. We can't have a light logo coz it needs to be printed out on white pages and all. We need to come back to the banner for this, will ping you after pushing a bunch of updates in the next hour.

**Comment by sidsrivast** [comment]
Tathagata, the website is looking pretty good now (I’ve been viewing the master branch copy). It looks like we will be ready to share with J. soon after addressing any minor issues that arise in the discussion tomorrow.

A few points to discuss tomorrow:

- Twitter feed could be moved to the right to reserve the left column for menus and dates. We can also make it shorter (it scrolls anyway) to fit ~3 past tweets
- Banner gets scaled in mobile versions, making the title text illegible.
-  List of Calls etc. look better if the background and borders are completely transparent and the text is white. Let’s discuss a few options along these lines if you have other ideas.
- Spacing between list items in deadlines is too much

**Comment by sidsrivast** [comment]
No worries. Your selection of pictures tends to be good... Since the banner scales, why not judiciously place the logo over a brighter image? See if it’s easy to do, otherwise we can talk tomorrow...
