### ISSUE TITLE
minor edits

### ISSUE THREAD

**Issue by TathagataChakraborti** [TathagataChakraborti/ICAPS2019#17]
- mobile version background
- twitter on the right
- banner fade
- call go to menu
- color on hover
- cfp page
- char before copyright

**Comment by TathagataChakraborti** [comment]
Twitter embed looks too big on the right.

**Comment by TathagataChakraborti** [comment]
Banner fade now color-wash instead of white-wash

**Comment by TathagataChakraborti** [comment]
Done!

**Comment by sidsrivast** [comment]
Please, not back on the left!!!

--
Siddharth Srivastava
Assistant Professor | CS | ASU
